### ISSUE TITLE
CI configuration

### ISSUE THREAD

**Issue by gsvgit** [gsvgit/PySymGym#1]
- [x] style checking
- [x] dependabot
- [x] tests
- [x] End-To-End pipeline test (without GPU)
     - Build maps.
     - Build game server.
     - Run all steps to train final model on small dataset.

**Comment by emnigma** [comment]
style checking: https://github.com/gsvgit/PySymGym/pull/8

**Comment by gsvgit** [comment]
End-To-End pipeline: #43
