### ISSUE TITLE
Current submodule command in README doesn't work

### ISSUE THREAD

**Issue by emnigma** [gsvgit/PySymGym#18]
![image](https://github.com/gsvgit/PySymGym/assets/40598909/314501a1-a19c-4fe0-a552-ff059198d982)

`git clone --recurse-submodules https://github.com/gsvgit/PySymGym.git` does not load submodules. I've used `git submodule update --init --recursive` instead, it did work:

![image](https://github.com/gsvgit/PySymGym/assets/40598909/5aff69ea-466c-49db-8869-5397936ce953)

Should we change command in README?

**Comment by gsvgit** [comment]
Yes, we should. 
@emnigma can you update README?

**Comment by emnigma** [comment]
> @emnigma can you update README?

sure
