### ISSUE TITLE
Create folder if does not exist

### ISSUE THREAD

**Issue by gsvgit** [gsvgit/PySymGym#38]
For these folders:
- https://github.com/gsvgit/PySymGym/blob/dev/AIAgent/config.py#L70
- https://github.com/gsvgit/PySymGym/blob/dev/AIAgent/config.py#L73

**Comment by emnigma** [comment]
I think, the issue meant these lines

<img width="588" alt="image" src="https://github.com/gsvgit/PySymGym/assets/40598909/31352216-532b-4206-8424-24c702355cf8">

Currently `./report/epochs_tables/` and `./report/timeouted_agents/` dirs are created automatically
