### ISSUE TITLE
Client should sent to server specific GameMap, not dataset

### ISSUE THREAD

**Issue by gsvgit** [gsvgit/PySymGym#7]
Communication protocol reworking required. Client should sent fully configured GameMap to play, not dataset and map id.

- [x] Client-side protocol
- [x] Server-side protocol

**Comment by emnigma** [comment]
Properties example:

"StepsToPlay": 2000,
"DefaultSearcher": "BFS",
"StepsToStart": 100,
"AssemblyFullName": "ManuallyCollected.dll",
"NameOfObjectToCover": "BinarySearch",
"MapName": "BinarySearch_100_BFS"

**Comment by emnigma** [comment]
#26
